/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRoute } from './routes/_authenticated'
import { Route as AuthRoute } from './routes/_auth'
import { Route as AuthenticatedIndexRoute } from './routes/_authenticated/index'
import { Route as AuthenticatedStocksSymbolRoute } from './routes/_authenticated/stocks/$symbol'
import { Route as AuthSignUpRoute } from './routes/_auth/sign-up'
import { Route as AuthSignInRoute } from './routes/_auth/sign-in'

// Create/Update Routes

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren([
  AuthenticatedIndexRoute,
  AuthenticatedStocksSymbolRoute,
])

const AuthRouteWithChildren = AuthRoute._addFileChildren([
  AuthSignUpRoute,
  AuthSignInRoute,
])

const rootRouteWithChildren = rootRoute._addFileChildren([
  AuthenticatedRouteWithChildren,
  AuthRouteWithChildren,
])

// Create and export the route tree

export const routeTree = rootRouteWithChildren

/* prettier-ignore-end */